name: Terraform Pipeline
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  bootstrap:
    uses: ulse-amit1/repoB/.github/workflows/bootstrap.yml@main

    with:
      organization: HCL-TERRA-TEAM
      workspace_name: dev-workspace
    secrets:
      TF_API_TOKEN:      ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID:   ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:   ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #  fmt:
  #    needs: bootstrap-workspace
  #    uses: ulse-amit1/repoB/.github/workflows/terraform-fmt.yml@main
  #    with:
  #      working_directory: network/env/dev

  validate:
    uses: ulse-amit1/repoB/.github/workflows/terraform-validate.yml@main

    with:
      working_directory: network/env/dev
    secrets: 
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  tflint:
    # needs: validate
    uses: ulse-amit1/repoB/.github/workflows/tflint.yml@main

    with:
      working_directory: network/env/dev

  trivy:
    needs: tflint
    uses: ulse-amit1/repoB/.github/workflows/trivy.yml@main


  terraform-test:
    needs: trivy
    uses: ulse-amit1/repoB/.github/workflows/terraform-test.yml@main

    with:
      working_directory: network/env/dev
    secrets: 
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  plan:
    needs: terraform-test
    uses: ulse-amit1/repoB/.github/workflows/terraform-plan.yml@main

    with:
      working_directory: network/env/dev
    secrets:
      TF_API_TOKEN:      ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID:   ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:   ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  opa:
    needs: plan
    uses: ulse-amit1/repoB/.github/workflows/opa.yml@main


  manual-approval:
    needs: opa
    runs-on: ubuntu-latest
    environment: Manual-Approval-Task
    steps:
      - name: Waiting For Approval
        run: echo "Manual approval completed"

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - manual-approval
    uses: ulse-amit1/repoB/.github/workflows/terraform-apply.yml@main

    with:
      working_directory: network/env/dev
    secrets:
      TF_API_TOKEN:      ${{ secrets.TF_API_TOKEN }}
      AZURE_CLIENT_ID:   ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID:   ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
